[package]
name = "mojang-leveldb"
version = "0.3.0"
edition = "2021"
build = "build.rs"
description = "LevelDB with Zlib support for Minecraft"
license="MIT"

[dependencies]
thiserror = "1.0.61"

[build-dependencies]
cmake = "0.1.50"
bindgen = "0.69.4"
