[package]
name = "mojang-leveldb"
version = "0.7.0"
edition = "2021"
build = "build/main.rs"
description = "LevelDB with Zlib support for Minecraft"
license = "MIT"

[dependencies]
thiserror = "1.0.61"
[[test]]
name = "iter_test"
[build-dependencies]
bindgen = "0.69.4"
cc = "1.1.7"
